tap "d12frosted/emacs-plus"
tap "domt4/autoupdate"
tap "ethereum/ethereum"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "thoughtbot/formulae"
brew "awscli"
brew "bat"
brew "coreutils"
brew "cuetools"
brew "dive"
brew "docker-completion"
brew "docker-compose-completion"
brew "duti"
brew "exa"
brew "exercism"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "helm"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "lazydocker"
brew "openjdk"
brew "leiningen"
brew "mas"
brew "minikube"
brew "minimal-racket"
brew "ncdu"
brew "neovim", args: ["HEAD"]
brew "prettyping"
brew "ripgrep"
brew "ripgrep-all"
brew "shellcheck"
brew "shntool"
brew "skaffold"
brew "solidity"
brew "switchaudio-osx"
brew "terminal-notifier"
brew "tldr"
brew "unar"
brew "volta"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "jakehilborn/jakehilborn/displayplacer"
brew "qmk/qmk/qmk", link: false
brew "thoughtbot/formulae/rcm"
cask "adoptopenjdk"
cask "balenaetcher"
cask "blackhole-2ch"
cask "calibre"
cask "dash"
cask "discord"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "fritzing"
cask "google-chrome"
cask "iina"
cask "intellij-idea-ce"
cask "karabiner-elements"
cask "keycastr"
cask "kicad"
cask "microsoft-auto-update"
cask "monitorcontrol"
cask "now"
cask "obs"
cask "obsidian"
cask "phoenix"
cask "qmk-toolbox"
cask "quicklook-json"
cask "slack"
cask "supercollider"
cask "tor-browser"
cask "transmission"
cask "tunnelblick"
cask "vimr"
cask "visual-studio-code"
cask "zoom"
cask "zotero"
mas "1Blocker", id: 1365531024
mas "Amphetamine", id: 937984704
mas "Are.na for Safari", id: 1497800947
mas "Capo", id: 696977615
mas "Developer", id: 640199958
mas "Endel", id: 1484348796
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Octotree", id: 1457450145
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Reeder", id: 1529448980
mas "Telegram", id: 747648890
mas "TextSniper", id: 1528890965
mas "Vimari", id: 1480933944
