tap "d12frosted/emacs-plus"
tap "derailed/k9s"
tap "domt4/autoupdate"
tap "ethereum/ethereum"
tap "fsouza/prettierd"
tap "gcenx/wine"
tap "hashicorp/tap"
tap "helix-editor/helix"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "noborus/tap"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "thoughtbot/formulae"
brew "act"
brew "awscli"
brew "bat"
brew "colima"
brew "coreutils"
brew "cuetools"
brew "dive"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper-ecr"
brew "dos2unix"
brew "duti"
brew "exa"
brew "exercism"
brew "fd"
brew "harfbuzz"
brew "libass"
brew "pango"
brew "ffmpeg"
brew "findutils"
brew "fio"
brew "folly"
brew "fzf"
brew "fzy"
brew "gh"
brew "gibo"
brew "git"
brew "glow"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "python@3.10"
brew "helm"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "openjdk"
brew "leiningen"
brew "librsvg"
brew "lua-language-server"
brew "mas"
brew "minikube"
brew "minimal-racket"
brew "mitmproxy"
brew "ncdu"
brew "neovim", args: ["HEAD"]
brew "pinentry-mac"
brew "prettyping"
brew "ripgrep"
brew "ripgrep-all"
brew "shellcheck"
brew "shntool"
brew "skaffold"
brew "solidity"
brew "stylua"
brew "switchaudio-osx"
brew "terminal-notifier"
brew "terraformer"
brew "tldr"
brew "unar"
brew "volta"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "yt-dlp", link: false
brew "zbar"
brew "zsh"
brew "derailed/k9s/k9s"
brew "hashicorp/tap/terraform"
brew "jakehilborn/jakehilborn/displayplacer"
brew "noborus/tap/ov"
brew "qmk/qmk/qmk", link: false
brew "thoughtbot/formulae/rcm"
cask "adoptopenjdk"
cask "balenaetcher"
cask "blackhole-2ch"
cask "brave-browser"
cask "calibre"
cask "dash"
cask "discord"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "iina"
cask "intellij-idea-ce"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "keycastr"
cask "logseq"
cask "michaelvillar-timer"
cask "microsoft-auto-update"
cask "monitorcontrol"
cask "mullvadvpn"
cask "musescore"
cask "neovide"
cask "now"
cask "obs"
cask "obsidian"
cask "openscad"
cask "patchwork"
cask "phoenix"
cask "qmk-toolbox"
cask "quicklook-json"
cask "rectangle"
cask "slack"
cask "supercollider"
cask "tor-browser"
cask "transmission"
cask "tunnelblick"
cask "unofficial-wineskin"
cask "vimr"
cask "visual-studio-code"
cask "zoom"
cask "zotero"
mas "1Blocker", id: 1365531024
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Are.na for Safari", id: 1497800947
mas "Capo", id: 696977615
mas "Developer", id: 640199958
mas "Endel", id: 1484348796
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Octotree", id: 1457450145
mas "Outline", id: 1356178125
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Pine Player", id: 1112075769
mas "Reeder", id: 1529448980
mas "Telegram", id: 747648890
mas "TextSniper", id: 1528890965
mas "uBlacklist for Safari", id: 1547912640
mas "Vimari", id: 1480933944
mas "Vinegar", id: 1591303229
mas "VOX", id: 461369673
